name: Opened pull requests ➡️ In Progress

on:
  pull_request:
    types: [opened]
jobs:
  add-pr-to-project-board:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.5.0
        with:
          repo-token: "${{ secrets.SYSTEMSOFT_TOKEN }}"
          project: "MVP"
          column: "Review In Progress"
