name: Continuous Integration 🏁

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Continuous Integration 🏁 ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: cd frontend && npm ci
      - run: cd frontend && SENTRY_ORG=${{ secrets.SENTRY_ORG }} SENTRY_PROJECT=${{ secrets.SENTRY_PROJECT }} SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }} npm run build --if-present
