name: New issues ➡️ Backlog

on:
  issues:
    types: [opened, assigned]
jobs:
  move-assigned-issue-on-project-board:
    runs-on: ubuntu-latest
    steps:
      - name: Opened issue ➡️ Backlog
        uses: alex-page/github-project-automation-plus@v0.5.0
        if: github.event.action == 'opened'
        with:
          repo-token: "${{ secrets.SYSTEMSOFT_TOKEN }}"
          project: "MVP"
          column: "Backlog"

      - name: New issues ➡️ Backlog
        uses: alex-page/github-project-automation-plus@v0.5.0
        if: github.event.action == 'assigned'
        with:
          repo-token: "${{ secrets.SYSTEMSOFT_TOKEN }}"
          project: "MVP"
          column: "In Progress"
